CREATE TABLE minions(
   id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
   name VARCHAR(45) NOT NULL,
   age INT NOT NULL
);

CREATE TABLE towns(
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(45) NOT NULL
);